LDLIBS=-L$LD_LIBRARY_PATH -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_objdetect -lopencv_calib3d -lopencv_features2d -lopencv_nonfree -lopencv_flann -lm

targets: filter2D_demo
